version: "3"

services:
  app:
    user: $UID:$GID
    build:
      context: .
    ports:
      - "7000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
